# Generated by Django 2.0.3 on 2018-03-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='include',
            name='restaurantID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='include',
            unique_together={('foodName', 'restaurantID', 'time', 'orderLocation', 'userID')},
        ),
        migrations.RemoveField(
            model_name='include',
            name='restaurantLocation',
        ),
        migrations.RemoveField(
            model_name='include',
            name='restaurantName',
        ),
    ]
