# Generated by Django 2.0.3 on 2018-04-18 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_include_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('cuisineName', models.CharField(default='chinese', max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=1)),
                ('cuisineName', models.CharField(default='chinese', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='order',
            name='restaurantID',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sharedorder',
            name='restaurantID',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sharedorder',
            name='status',
            field=models.CharField(default='unfullfilled', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='sharedOrderID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sharedorder',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('userID', 'cuisineName')},
        ),
        migrations.RemoveField(
            model_name='sharedorder',
            name='orderLocation',
        ),
        migrations.RemoveField(
            model_name='sharedorder',
            name='userID',
        ),
    ]
