# Generated by Django 2.0.3 on 2018-04-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180418_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisinetype',
            name='cuisineName',
            field=models.CharField(default='Chinese', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='cuisineName',
            field=models.CharField(default='Chinese', max_length=30),
        ),
    ]
