# Generated by Django 2.0.3 on 2018-04-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180418_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='include',
            old_name='restaurantID',
            new_name='foodID',
        ),
        migrations.AddField(
            model_name='include',
            name='orderID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='include',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='include',
            name='foodName',
        ),
        migrations.RemoveField(
            model_name='include',
            name='orderLocation',
        ),
        migrations.RemoveField(
            model_name='include',
            name='time',
        ),
        migrations.RemoveField(
            model_name='include',
            name='userID',
        ),
    ]
