# Generated by Django 2.0.3 on 2018-04-18 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180418_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sharedOrderID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.SharedOrder'),
        ),
    ]
