# Generated by Django 2.0.3 on 2018-04-19 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180418_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sharedOrderID',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.SharedOrder'),
        ),
    ]
